name: 🔴 Bug report
description: Something is not working as expected.
title: 🔴 <bug name>
labels: bug

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!!!
  - type: textarea
    attributes:
      label: Description
      placeholder: >-
        A clear and concise description of what the bug is...
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: To Reproduce
      description: >-
        Steps to reliably reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Behavior
      placeholder: >-
        A clear and concise description of what you expected to happen...
    validations:
      required: true
      
  - type: textarea
    attributes:
      label: Version Information
      description: >-
         click on the version number on the welcome screen
      value: |
        Spotify-Clone: [e.g. 0.0.x-alpha.y]
        macOS: [e.g. 13.2.1]
        iOS: [e.g. 17.0]
        Chrome: [e.g. 15.7.8]
        Safari: [e.g. 15.7.8]
        

  - type: textarea
    attributes:
      label: Additional Context
      placeholder: >-
        Any other context or considerations about the bug...
      
  - type: textarea
    attributes:
      label: Screenshots
      placeholder: >-
        If applicable, please provide relevant screenshots or screen recordings...

  - type: dropdown
    id: versions
    attributes:
      label: Which version of the app are you using?
      description: If this issue is occurring on more than 1 version of the app, select the appropriate versions.
      multiple: true
      options:
       - 0.1.0
       - 0.x.x
    validations:
      required: true

  - type: checkboxes
    id: new-bug
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true

  - type: checkboxes
    id: read-code-of-conduct
    attributes:
      label: Have you read the Code of Conduct?
      description: Please read the CODE OF CONDUCT.
      options:
      - label: I have read the CODE OF CONDUCT 🏢
        required: true
